---
title: "Coronavírus: Atualização diária dos casos e mortes no Brasil"
author: Cainã Max Couto-Silva
date: "`r Sys.Date()`"
slug: "coronavirus-atualização-diaria-dos-casos-e-mortes-no-brasil"
categories:
  - Python
  - Human Population
tags:
  - python
  - codiv-19
  - coronavirus
banner: img/banners/codiv19.png
summary: >
  Acompanhe aqui a atualização diária dos casos e mortes por COVID-19 no Brasil e no mundo,
  por meio de gráfico simples e interativos.
---

```{r settings, echo=FALSE}
library(reticulate)
knitr::opts_knit$set(root.dir = "~/cmcouto.silva@usp.br/portfolio/blog")
iframe <- function(fig) {
  paste0('<iframe scrolling="no" width="100%" height="545px" src="/',
         fig,'" frameborder="0" allowfullscreen></iframe>')
}
```

```{python html_dirs, echo=FALSE, engine.path = '/home/cmcouto-silva/miniconda3/bin/python'}
from os import makedirs
makedirs('static/files/blog/codiv19_daily_update', exist_ok=True)
```

### Gráficos Interativos da Incidência de COVID-19 no Brasil

&nbsp;

Este é um post informativo sobre a incidência de coronavírus no Brasil, cujos dados utilizados foram retirados da <a href="https://ourworldindata.org/coronavirus-source-data" target="_blank">Organização Mundial da Saúde</a> e estão sendo atualizados diaramente (vide última atualização).

Os gráficos e as datas são gerados de forma automática através do download dos dados da OMS. Todos os gráficos deste post são interativos, portanto,  pode-se, por exemplo, desativar dados clicando nas legendas, e ampliar os gráficos.

Post atualizado pela última vez em: ```r format(Sys.time(), "%d de %B de %Y, %H:%Mh (Horário de Brasília ─  UTC-3)")```.
  
&nbsp;

```{python codiv19_brazil, echo=FALSE, engine.path = '/home/cmcouto-silva/miniconda3/bin/python'}
import locale
import pandas as pd
import plotly.io as pio
import plotly.express as px
import plotly.graph_objects as go

df = pd.read_csv('https://covid.ourworldindata.org/data/ecdc/full_data.csv', parse_dates = ['date'])
df.rename({'date':'Data', 'location':'País'}, axis=1, inplace=True)
df['dt'] = df.Data.dt.strftime('%d de %B de %Y')
df = df[df.País!='World']
df = df[df.total_cases>0]

df_casos = df.copy()
df_mortes = df.copy()

df_casos['Categoria'] = 'Casos'
df_casos['Quantidade'] = df_casos['total_cases']

df_mortes['Categoria'] = 'Mortes'
df_mortes['Quantidade'] = df_mortes['total_deaths']

df_target = pd.concat([df_casos, df_mortes])

br = df_target[df_target.País=='Brazil']
es = df_target[df_target.País=='Spain']

br = br[br.Quantidade>0]
es = es[es.Quantidade>0]

tmp=locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
tmp=locale.setlocale(locale.LC_TIME, "pt_BR.UTF-8")

country = br

if(country.País.unique()=='Brazil'):
    prep = "no Brasil"
    tick_vals = pd.date_range(country.Data.min(), country.Data.max())
    tick_labels = tick_vals.strftime('%b %d')
else:
    prep = "na Espanha"
    tick_vals = pd.date_range(country.Data.min(), country.Data.max(), freq='2D')
    tick_labels = tick_vals.strftime('%b %d')

fig = px.scatter(country, x='Data', y='Quantidade', color="Categoria", template="simple_white", 
                title=f'<b>Indicência de COVID-19 {prep}</b>', hover_name='dt',
                 color_discrete_sequence = ["#1f78b4", "#ff0000"])

fig = fig.update_traces(mode='lines+markers', line_width=3, marker_size=10)
fig = fig.update_xaxes(title=None, tickangle=-90, tickvals=tick_vals, ticktext=tick_labels)
fig = fig.update_yaxes(title=None)
fig = fig.update_xaxes(showgrid=True)
fig = fig.update_yaxes(showgrid=True)

fig = fig.update_layout(legend=dict(title='Categoria'), font_size=13)

for i in range(len(fig.data)):
    fig.data[i]['hovertemplate'] = ''.join (
        ['<b>%{hovertext}<br></b>Categoria = ', fig.data[i]['name'], '<br>Quantidade = %{y:.i}'])

pio.write_html(fig, file='static/files/blog/codiv19_daily_update/brazil.html', auto_open=False)
```

`r iframe('files/blog/codiv19_daily_update/brazil.html')`

```{python codiv19_world, echo=FALSE, engine.path = '/home/cmcouto-silva/miniconda3/bin/python'}
top10_cases = df.groupby('País').max().sort_values('total_cases', ascending=False).index[:10]
top10_newcases = df.groupby('País').max().sort_values('new_cases', ascending=False).index[:10]
top10_deaths = df.groupby('País').max().sort_values('total_deaths', ascending=False).index[:10]
top10_newdeaths = df.groupby('País').max().sort_values('new_deaths', ascending=False).index[:10]

def plt_top10(top10, target_col, hoverinfo, title):
    """Make a plot from top10 countries"""
    
    data = df.copy()
    data = data[data[target_col] > 0]
    
    country = top10[0]
    hovertemplate = f'<b>{country}</b><br><br>Data: %{{x|%B %d, %Y}}<br>{hoverinfo}: %{{y:i}}<extra></extra>'
    
    fig = go.Figure(data=go.Figure(
        go.Scatter (
        x=data[data.País==country].Data,
        y=data[data.País==country][target_col],
        name=country, mode = 'lines+markers', hovertemplate = hovertemplate, opacity=.9
    )))

    for i in range(1, 10):
        country = top10[i]
        hovertemplate = f'<b>{country}</b><br><br>Data: %{{x|%B %d, %Y}}<br>{hoverinfo}: %{{y:i}}<extra></extra>'

        fig.add_trace(go.Scatter (
        x=data[data.País==country].Data,
        y=data[data.País==country][target_col],
        name=country, mode = 'lines+markers', hovertemplate = hovertemplate
        ))

    fig = fig.update_layout(template='simple_white', title=f'<b>{title}</b>', font_size=13)
    fig = fig.update_traces(mode='lines+markers', line_width=3, marker_size=10)
    fig = fig.update_xaxes(title=None)
    fig = fig.update_yaxes(title=None)
    fig = fig.update_xaxes(showgrid=True)
    fig = fig.update_yaxes(showgrid=True)
    return fig

top10_cases = plt_top10(top10_cases, 'total_cases',
          hoverinfo='Totalidade de casos',
          title='Países com maiores quantidades totais de casos')

top10_newcases = plt_top10(top10_newcases, 'new_cases',
          hoverinfo='Novos casos',
          title='Países com maiores quantidades de NOVOS de casos')

top10_deaths = plt_top10(top10_deaths, 'total_deaths',
          hoverinfo='Totalidade de mortes',
          title='Países com maiores quantidades totais de mortes')

top10_newdeaths = plt_top10(top10_newdeaths, 'new_deaths',
          hoverinfo='Novos casos de mortes',
          title='Países com maiores quantidades NOVOS casos de mortes')


pio.write_html(top10_cases, file = 'static/files/blog/codiv19_daily_update/top10_cases.html', auto_open=False)
pio.write_html(top10_newcases, file = 'static/files/blog/codiv19_daily_update/top10_newcases.html', auto_open=False)
pio.write_html(top10_deaths, file = 'static/files/blog/codiv19_daily_update/top10_deaths.html', auto_open=False)
pio.write_html(top10_newdeaths, file = 'static/files/blog/codiv19_daily_update/top10_newdeaths.html', auto_open=False)

df_map = df.groupby('País', as_index=False).max().rename({'total_cases':'Totalidade de casos'}, axis=1)
fig = px.choropleth(df_map, locations="País", locationmode='country names',
                    color="Totalidade de casos", hover_name="País",
                    color_continuous_scale='Reds', template=None
                   )
fig.data[0].hovertemplate = '<b>%{hovertext}</b><br>%{z}'
fig.layout.coloraxis.colorbar.title.text = '' #'<b>Totalidade de casos</b>'
fig.layout.title= '<b>Totalidade de casos no mundo</b>'
fig = fig.update_layout(title_x=0.1)

pio.write_html(fig, file = 'static/files/blog/codiv19_daily_update/top10_map.html', auto_open=False)

south_america = ['Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela']
central_america = ['Panama', 'Costa Rica', 'Nicaragua', 'Honduras', 'El Salvador', 'Guatemala', 'Belize']
others = ['Bahamas', 'Cuba', 'Jamaica', 'Haiti', 'Dominican Republic']

df_amr = df_map[df_map.País.isin(south_america+central_america+others)]

fig = px.choropleth(df_amr, locations="País", locationmode='country names',
                    color="Totalidade de casos", # lifeExp is a column of gapminder
                    hover_name="País", # column to add to hover information
                    color_continuous_scale='YlOrRd', template=None
                   )
fig.data[0].hovertemplate = '<b>%{hovertext}</b><br>%{z}'
fig.layout.coloraxis.colorbar.title.text = '' #'<b>Totalidade de casos</b>'
fig.layout.title= '<b>Totalidade de casos na América Latina</b>'
fig = fig.update_layout(title_x=0.48)
fig = fig.update_geos(lataxis_range=[-55, 25], lonaxis_range=[-120, -30])

pio.write_html(fig, file = 'static/files/blog/codiv19_daily_update/central_south_america_map.html', auto_open=False)
```

&nbsp;

### Gráficos Interativos da Incidência de COVID-19 no Mundo

Além do Brasil, aprensento os dados dos 10 países com maiores índices de casos e mortes,
totais e emergentes, <br>de COVID-19 no mundo:

`r iframe("files/blog/codiv19_daily_update/central_south_america_map.html")`
`r iframe("files/blog/codiv19_daily_update/top10_map.html")`

`r iframe("files/blog/codiv19_daily_update/top10_cases.html")`
`r iframe("files/blog/codiv19_daily_update/top10_newcases.html")`
`r iframe("files/blog/codiv19_daily_update/top10_deaths.html")`
`r iframe("files/blog/codiv19_daily_update/top10_newdeaths.html")`

```{python codiv19_conclusions, echo=FALSE, engine.path = '/home/cmcouto-silva/miniconda3/bin/python'}
# World
world_maior_incidencia = df.iloc[df.total_cases.argmax()][['País', 'total_cases']]
world_maior_mortalidade = df.iloc[df.total_deaths.argmax()][['País', 'total_deaths']]

world_last_5days = df.groupby('País', as_index=False).tail().groupby('País', as_index=False).sum()

world_newcases = world_last_5days.iloc[world_last_5days.new_cases.argmax()][['País', 'new_cases']]
world_newdeaths = world_last_5days.iloc[world_last_5days.new_deaths.argmax()][['País', 'new_deaths']]

# Latin America
df_amr = df[df.País.isin(south_america+central_america+others)]
amr_maior_incidencia = df_amr.iloc[df_amr.total_cases.argmax()][['País', 'total_cases']]
amr_maior_mortalidade = df_amr.iloc[df_amr.total_deaths.argmax()][['País', 'total_deaths']]

amr_last_5days = df_amr.groupby('País', as_index=False).tail().groupby('País', as_index=False).sum()

amr_newcases = amr_last_5days.iloc[amr_last_5days.new_cases.argmax()][['País', 'new_cases']]
amr_newdeaths = amr_last_5days.iloc[amr_last_5days.new_deaths.argmax()][['País', 'new_deaths']]

```


### Conclusões (automáticas)

&nbsp;

#### Mundo
- País com maior incidência de CODIV-19 no mundo:
````r py$world_maior_incidencia[1]` (n=`r format(py$world_maior_incidencia[2], scientific=F)`)```.
- País com mais novos casos de CODIV-19 nos últimos 5 dias:
````r py$world_maior_incidencia[1]` (n=`r format(py$world_maior_incidencia[2], scientific=F)`)```.
- País com maior número absoluto de morte em pessoas diagnósticadas com CODIV-19:
````r py$world_maior_incidencia[1]` (n=`r format(py$world_maior_incidencia[2], scientific=F)`)```.
- País com mais novos casos de morte em pessoas diagnósticadas com CODIV-19 nos últimos 5 dias:
````r py$world_maior_incidencia[1]` (n=`r format(py$world_maior_incidencia[2], scientific=F)`)```.

#### Américas Central e do Sul
- País latino com maior incidência de CODIV-19:
````r py$amr_maior_incidencia[1]` (n=`r format(py$amr_maior_incidencia[2], scientific=F)`)```.
- País latino com mais novos casos de CODIV-19 nos últimos 5 dias:
````r py$amr_newcases[1]` (n=`r format(py$amr_newcases[2], scientific=F)`)```.
- País latino com maior número absoluto de morte em pessoas diagnósticadas com CODIV-19:
````r py$amr_maior_mortalidade[1]` (n=`r format(py$amr_maior_mortalidade[2], scientific=F)`)```.
- País latino com mais novos casos de morte em pessoas diagnósticadas com CODIV-19 nos últimos 5 dias:
````r py$amr_newdeaths[1]` (n=`r format(py$amr_newdeaths[2], scientific=F)`)```.

&nbsp;

O código deste post pode ser acessado através <a href="https://github.com/cmcouto-silva/blog_files/blob/master/content/blog/coronavirus-atualiza%C3%A7%C3%A3o-diaria-dos-casos-e-mortes-no-brasil.Rmd" target="_blank">deste link</a> via github.

&nbsp;
