---
title: Genes sob seleção natural nos Andes
author: Cainã Max Couto-Silva
date: '2020-03-25'
slug: genes-sob-seleção-natural-nos-andes
categories:
  - Pesquisa
tags:
  - Genética
  - Genética de populações
banner: "img/banners/SciRep_2018.png"
summary: >
  Relato do meu primeiro artigo científico, publicado na _Scientific Reports_, 
  mostrando evidências de genes que possivelmente foram selecionados para facilitar
  a adaptação de populações indígenas nas altas altitudes dos Andes.
---

<meta property="og:image" content="https://cmcouto-silva.github.io/img/banners/SciRep_2018.png" />

<style>

body {
text-align: justify
}

.center {
    text-align: center;
}

.caption {
    text-align: justify;
    margin: 10px 20px;
    font-size: 13px
}

</style>


# Genes sob seleção natural nos Andes

---

&nbsp;

No dia 24/08, foi publicado meu primeiro artigo científico. Logo após, houve uma entrevista que gerou uma matéria sobre o artigo, publicada na **Revista FAPESP**, cujo link se encontra disponível <a href="http://revistapesquisa.fapesp.br/2018/09/20/uma-adaptacao-singular-as-alturas/" target="_blank">aqui</a>. No artigo, <a href="https://www.nature.com/articles/s41598-018-31100-6/" target="_blank">publicado na  <b>Scientific Reports</b></a>, mostra pela primera vez a importância de três genes para populações nativas Americanas que vivem em altas altitudes.

Verificou-se que determinadas variantes presentes nestes genes apresentam fortes sinais de seleção natural (positiva) em populações Andinas, que vivem em altas altitudes, locais caracterizados pela baixa pressão atmosférica (_i.e._ baixa concentração de oxigênio).

Dentre a metodologia empregada, aplicou-se primeiramente um teste denominado **PBS** (**_Population Branch Statistics_**), que se fundamenta na comparação dos índices de **Fst** entre três populações: uma população-alvo e com uma população próxima para comparação direta, ditas como populações-irmãs, e uma terceira população ancestral de ambas. O princípio deste teste é bem simples: espera-se que as populações-irmãs sejam geneticamente mais próximas entre si quando comparadas à população ancestral, do contrário, eis um indício de seleção positiva.

Por considerar um cenário demográfico, PBS consiste em um teste amplamente utilizado para detectar indícios de seleção natural (sempre em conjunto com outros métodos). Através dele se identificou **SNPs** potencialmente sobre seleção em cinco genes: _SP100_, _TMEM38B_, _AS3MT_, _DUOX2_ e _CLC._ Destes genes, _TMEM38B_ e _AS3MT_ já foram previamente identificados em outros estudos com populações de altas altitudes.

&nbsp;

<div class="center">
![**Figura 1. Populations Branch Statistics**. Alelos pertencentes aos genes _SP100_ (cromossomo 2), _TMEM38B_ (cromossomo 9), _AS3MT_ (cromossomo 10), _DUOX2_ (cromossomo 15), e _CLC_ (cromossomo 19), encontram-se em alta frequência na população Andina, quando comparadas às populações amazônicas vivendo em baixas altitudes, considerando povos da América Central como grupo externo (ancestral).](/img/blog/SciRep_Andes/fig1.png){width=75% height=70%}
</div>

&nbsp;

Os resultados gerados pelo método PBS foram então corroborados com as análises seguintes. Primeiramente verificou-se que estas frequências elevadas nos Andes não aparentam ser devido à eventos demográficos, que poderiam também explicar a diferença estatisticamente significante entre os genótipos (vide figura 2 do artigo original). Posteriormente, testes baseados no **desequilíbrio de ligação** (LD, do inglês, **_linkage disequilibrium_**) ─ **_hard sweeps_** ─ foram aplicados para identificar sinais de seleção positiva. Os testes de LD focam na extensão de *homozigose* dos haplótipos (**EHH**) que, por sua vez, possui como fundamento conceitos clássicos da biologia referentes à herança genética (muito importante, neste caso, o **_crossing over_**).

Em conjunto, as diferentes técnicas (PBS, baseado nos índices de Fst) e análises de EHH (_e.g._ iHS, XP-EHH, baseadas no desequiĺibrio de ligação) aplicadas no trabalho corroboraram entre si apontando um mesmo conjunto de SNPs nos seguintes genes: _SP100_, _DUOX2_ e _CLC._ Dados estes achados, os genes identificados foram então melhor estudados, de forma que mais duas análises foram realizadas: correlação entre altitude e frequência dos alelos e avaliação da expressão gênica.

Por expressão gênica, entende-se o quanto um gene é expresso ─ e consequentemtente a proteína é produzida ─ em determinadas regiões do corpo, como tecidos e órgãos. Para isso, foi utilizado um banco de dados públicos que contém informações de milhares de genes, mostrando os respectivos níveis de expressão gênica em diferentes tecidos do corpo humano. Verificou-se com isso que indivíduos homozigotos para os alelos que foram encontrados sob seleção apresentam maior nível de expressão gênica para as respectivas proteínas ─ SP100 e DUOX2. No caso de _DUOX2_, verificou-se que o gene é expresso principalmente na tireoide e pulmão, enquanto, _SP100_, nos músculos esqueléticos. Maiores informações disponíveis na discussão sobre cada um destes genes, logo abaixo.

Observou-se que a frequência dos alelos sob seleção nos Andes é maior quando comparado às demais populações, que vivem em baixas altitudes. O quadro e o mapa abaixo ilustram bem este cenário.

&nbsp;

<div class="center">
![Figura 2. Alelos sob potencial seleção são mais frequentes em povos vivendo em altas altitudes. (A) Gene _SP100_. (B) Gene _DUOX2._ (C) Gene _CLC._ No painel à esquerda, frequência dos alelos (maior frequência em vermelho) dos respectivos genes. No painel à direita, mostra os níveis de altitude no mapa. Obs: Esta ilustração corresponde à figura 3 do artigo original.](/img/blog/SciRep_Andes/fig3.png){width=80% height=10%}
</div>


<br>À fim de aumentar a confiabilidade destes dados, simulamos 10.000 populações de baixas altitudes com o mesmo tamanho e proporções genotípicas das populações originais do estudo (figura suplementar 2). Com isso, gerou-se um intervalo de confiança de 95% sobre o quanto esta frequência alélica deve variar nas populações de baixas altitudes. A frequência alélica nas populações de altas altitudes ─ Andinas ─ está muito além deste intervalo, fortalecendo assim a noção de que esta elevada frequência nas populações Andinas não é ao acaso, ou seja, que é provavelmente oriunda de um processo evolutivo.

&nbsp;

### Sobre os novos genes candidatos identificados

---

- **_SP100_**

Produz diferentes formas de proteínas que atuam no controle da atividade da p53, famosa por seu papel para evitar o estresse celular.  
_SP100_ também está diferencialmente expresso nos músculos esqueléticos. Interessantemente, um membro da via de sinalização HIF (_Hypoxia-Inducible Factor_), HIF-1, desempenha um papel essencial na regulação da homeostase do oxigênio, que inclui adaptações fisiológicas do músculo cardíaco e equelético em situações de hipóxia.

- **_DUOX2_**

_DUOX2_ é expresso em células epiteliais de vários tecidos, incluindo as vias respiratórias e o pulmão. Ele participa da via de sinalização do peróxido de oxigênio (H<sub>2</sub>O<sub>2</sub>), que é necessária para produção do hormônio da tireoide.

_DUOX2_ também está envolvido na produção de espécies reativas ao oxigênio (ROS), um bioproduto normal do metabolismo do oxigênio, que é prejudicial em grandes quantidades (porém ainda assim produzido em pessoas saudáveis). Em situações de estresse celular, como na hipóxia e exposição à UV decorrente de altas altitudes, há um aumento da produção de ROS. Na discussão do artigo, levanta-se uma série de trabalhos que correlacionam _DUOX2_ com a hipóxia.

Ademais, cabe ressltar que ROS tem um papel importante na angiogênese (_i.e._ formação de novos vasos sanguíneos) que, por sua vez, é uma importante resposta fisiológica ao estresse causado pela hipóxia.

- **CLC**:

_CLC_ (galactina-10) é um gene pouco estudado, e o único estudo funcional relacionando com hipóxia até a data de publicação do artigo, mostra que a hipóxia aumenta o acúmulo de eosinófilos e produção de proteína CLC, produzindo um atraso na *apoptose* (morte celular programada).

Proteínas muito similares à CLC possuem um papel essencial na gestação. Ainda que não tenha artigos científicos para corrobar a seguinte afirmação, é de conhecimento corrente que a gestação/parto é um problema comum em populações que vivem em altas altitudes. Portanto, talvez este seja um caminho que conecte CLC aos achados deste artigo.

&nbsp;

<div class="ref">

#### Referências

Artigo publicado na **_Scientific Reports_**:
[https://www.nature.com/articles/s41598-018-31100-6](https://www.nature.com/articles/s41598-018-31100-6)  
Matéria sobre o artigo publicado na **_Revista FAPESP_**:
[http://revistapesquisa.fapesp.br/2018/09/20/uma-adaptacao-singular-as-alturas/](http://revistapesquisa.fapesp.br/2018/09/20/uma-adaptacao-singular-as-alturas/)
</div>
